name: Tag on Version Update

on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true  # Only run if the PR is actually merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Check for existing tag
        id: tag_check
        run: |
          TAG_EXISTS=$(git tag -l "v${{ steps.version.outputs.version }}")
          if [ -n "$TAG_EXISTS" ]; then
            echo "Tag v${{ steps.version.outputs.version }} already exists. Skipping tagging."
            exit 0

      - name: Create and push tag
        if: steps.tag_check.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
