name: Version Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  check-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for package.json changes
        run: |
          if ! git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "package.json"; then
            echo "Error: package.json must be updated in this PR." && exit 1
          fi
