name: Version Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  check-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetches enough history for the diff command

      - name: Check for package.json changes
        run: |
          if ! git diff --name-only HEAD~1 HEAD | grep -q "package.json"; then
            echo "Error: package.json must be updated in this PR." && exit 1
          else
            echo "package.json has been updated in this PR."
          fi
